version: '3.8'

services:
  # 1. Banco Relacional Transacional (Core Business, IAM, Estoque)
  postgres:
    image: postgres:16-alpine
    container_name: obra360-postgres
    restart: always
    environment:
      POSTGRES_DB: obra360_db
      POSTGRES_USER: obra360_admin
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Banco NoSQL (Trilha de Auditoria, Logs Técnicos & Snapshots 3D)
  mongo:
    image: mongo:7.0
    container_name: obra360-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # 3. Mensageria Orientada a Eventos (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: obra360-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # 4. Apache Kafka (Event Streaming de Alta Performance)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: obra360-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: obra360-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pgdata:
  mongodata:
